export const INDIAN_TV_CHANNELS_LIST = [
  "star plus",
  "zee tv",
  "sony entertainment television (set)",
  "colors tv",
  "sab tv",
  "&tv",
  "star bharat",
  "mtv india",
  "channel v",
  "sony sab",
  "dd national",
  "sun tv",
  "vijay tv",
  "zee tamil",
  "colors tamil",
  "jaya tv",
  "raj tv",
  "news18 india",
  "ndtv india",
  "aaj tak",
  "times now",
  "cnn-news18",
  "republic tv",
  "india today",
  "abp news",
  "news nation",
  "cnbc tv18",
  "ndtv 24x7",
  "discovery channel india",
  "national geographic india",
  "history tv18",
  "cartoon network india",
  "pogo",
  "nick india",
  "disney channel india",
  "sony espn",
  "star sports",
  "ten sports",
  "dd sports",
  "mtv india",
  "vh1 india",
  "9xm",
  "b4u music",
  "zing",
  "zoom",
  "tlc india",
  "food food",
  "travel xp",
  "sony pix",
  "hbo india",
];

export const INDIAN_TV_SHOWS = [
  "taarak mehta ka ooltah chashmah",
  "yeh rishta kya kehlata hai",
  "kundali bhagya",
  "kumkum bhagya",
  "ishqbaaaz",
  "kasautii zindagii kay",
  "bigg boss",
  "indian idol",
  "dance india dance",
  "crime patrol",
  "balika vadhu",
  "diya aur baati hum",
  "saath nibhaana saathiya",
  "naagin",
  "jodha akbar",
  "bade achhe lagte hain",
  "mahabharat",
  "devon ke dev... mahadev",
  "sasural simar ka",
  "sasural genda phool",
  "pavitra rishta",
  "chakravartin ashoka samrat",
  "yeh hai mohabbatein",
  "saraswatichandra",
  "shaktimaan",
  "cid",
  "sarabhai vs sarabhai",
  "fir",
  "comedy nights with kapil",
  "the kapil sharma show",
  "indian matchmaking",
  "sacred games",
  "mirzapur",
  "paatal lok",
  "tarak mehta ka ooltah chashmah",
  "guddan tumse na ho payega",
  "ishq subhan allah",
  "qubool hai",
  "beyhadh",
  "kaisi yeh yaariaan",
  "ghum hai kisikey pyaar meiin",
  "anupamaa",
  "saath nibhaana saathiya 2",
  "indian pro music league",
  "super dancer",
  "khatron ke khiladi",
  "dus ka dum",
  "indian premier league (ipl)",
  "taarak mehta ka chhota chashmah",
];

export const GENRE = [
  "action",
  "adventure",
  "animated",
  "biography",
  "comedy",
  "crime",
  "dance",
  "disaster",
  "documentary",
  "drama",
  "erotic",
  "family",
  "fantasy",
  "found footage",
  "historical",
  "horror",
  "independent",
  "legal",
  "live Action",
  "martial Arts",
  "musical",
  "mystery",
  "noir",
  "performance",
  "political",
  "romance",
  "satire",
  "science fiction",
  "short",
  "silent",
  "slasher",
  "sports",
  "spy",
  "superhero",
  "supernatural",
  "suspense",
  "teen",
  "thriller",
  "war",
  "western",
];
